services:
  app-dev:
    build:
      context: .
    # command: npm run dev
    ports:
      - '3000:3000'
    env_file: .env.local
    # environment:
    #   - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
# app-prod:
#   build:
#     context: .
#     args:
#       - NODE_ENV=production
#   ports:
#     - '0.0.0.0:8000:3000'
